build:
  stage: build
  image: node:lts-bullseye
  script:
    - cd portfolio
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - portfolio/build/


pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  needs:
    - build
  script:
    - mv portfolio/build/ public
  artifacts:
    paths:
      - public
