build-front-end-job:
  stage: build
  image: node:lts-bullseye


  script:
    - cd portfolio
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - portfolio/build/
