build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - lint-test-job

  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/
